/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.college_event_management.pages;

import com.mycompany.college_event_management.database.AppState;
import com.mycompany.college_event_management.database.tables.Organizer;
import javax.swing.JFrame;
//import java.awt.Dimension;


/**
 *
 * @author supru
 */
public class org_homepage extends javax.swing.JFrame {

    /**
     * Creates new form org_homepage
     */
    public org_homepage() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        Organizer loggedInOrg = AppState.logedinOrg;
        NameValue.setText(loggedInOrg.organizerName);
        EmailValue.setText(loggedInOrg.organizeremail);
        PhoneValue.setText(loggedInOrg.organizerPhone);
        UsernameValue.setText(loggedInOrg.organizerUsername);
        //this.setSize(new Dimension(400, 300));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        NameText = new javax.swing.JLabel();
        NameValue = new javax.swing.JLabel();
        EmailText = new javax.swing.JLabel();
        EmailValue = new javax.swing.JLabel();
        PhoneText = new javax.swing.JLabel();
        UserNameText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        PhoneValue = new javax.swing.JLabel();
        UsernameValue = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameText.setText("Name: ");
        getContentPane().add(NameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        NameValue.setText("Name: ");
        getContentPane().add(NameValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        EmailText.setText("Email: ");
        getContentPane().add(EmailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        EmailValue.setText("Email: ");
        getContentPane().add(EmailValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        PhoneText.setText("Phone:");
        getContentPane().add(PhoneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        UserNameText.setText("Username:");
        getContentPane().add(UserNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 16, 37, -1));

        jLabel2.setText("Create a new event");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 169, 213, -1));

        jButton2.setText("jButton2");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jLabel4.setText("Existing events");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 110, -1));

        jButton3.setText("jButton3");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jLabel5.setText("Organizer details");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 110, -1));

        PhoneValue.setText("Phone:");
        getContentPane().add(PhoneValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        UsernameValue.setText("Username:");
        getContentPane().add(UsernameValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(org_homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(org_homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(org_homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(org_homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new org_homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmailText;
    private javax.swing.JLabel EmailValue;
    private javax.swing.JLabel NameText;
    private javax.swing.JLabel NameValue;
    private javax.swing.JLabel PhoneText;
    private javax.swing.JLabel PhoneValue;
    private javax.swing.JLabel UserNameText;
    private javax.swing.JLabel UsernameValue;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
