/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.college_event_management.pages;

import com.mycompany.college_event_management.Utils.EventTableModel;
import com.mycompany.college_event_management.database.AppState;
import com.mycompany.college_event_management.database.tables.Event;
import com.mycompany.college_event_management.database.tables.Organizer;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author supru
 */
public class org_homepage extends javax.swing.JFrame {

    /**
     * Creates new form org_homepage
     */
     private List<String> items = new ArrayList<>();

    public org_homepage() {
        initComponents();
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        Organizer loggedInOrg = AppState.logedinOrg;
        nametxt.setText(loggedInOrg.organizerName);
        emailtxt.setText(loggedInOrg.organizeremail);
        phonetxt.setText(loggedInOrg.organizerPhone);
        usernametxt.setText(loggedInOrg.organizerUsername);
        fetchEvents();
        ///fetchCompEvents();
        //this.setSize(new Dimension(400, 300));

    }
    private void fetchEvents(){
        var allEvents = Event.getEventsByOrganizerId();
        System.err.println("allEvents" + allEvents.size());
        //Table
        EventTableModel model = new EventTableModel(allEvents);
        Eventtab.setModel(model);
        
        //Pannel with delete
        for (Event e : allEvents) {
          items.add(e.eventName);
        }
        refreshItemList();
    }
    private void refreshItemList() {
        eventlist.removeAll();

        for (String item : items) {
            JPanel itemPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
            JLabel itemLabel = new JLabel(item);
            JButton deleteButton = new JButton("Delete");
            deleteButton.addActionListener((ActionEvent e) -> {
                items.remove(item);
                refreshItemList();
                // Revalidate and repaint to ensure UI updates are displayed
                eventlist.revalidate();
                eventlist.repaint();
            });

            itemPanel.add(itemLabel);
            itemPanel.add(deleteButton);
            eventlist.add(itemPanel);
            System.out.println("added "+ item);
        }

        // In case the list is empty, show a message
        if (items.isEmpty()) {
            eventlist.add(new JLabel("No items available."));
        }
    }
//    private void fetchCompEvents(){
//        var allEvents = Event.getEventsByOrganizerId();
//        System.err.println("allEvents" + allEvents.size());
//        //Table
//        EventTableModel model = new EventTableModel(allEvents);
//        Eventtab.setModel(model);
//        
//        //Pannel with delete
//        for (Event e : allEvents) {
//          items.add(e.eventName);
//        }
//        refreshItemList();
//    }
//    private void refresh() {
//        eventlist.removeAll();
//
//        for (String item : items) {
//            JPanel itemPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
//            JLabel itemLabel = new JLabel(item);
//            JButton deleteButton = new JButton("Delete");
//            deleteButton.addActionListener((ActionEvent e) -> {
//                items.remove(item);
//                refreshItemList();
//                // Revalidate and repaint to ensure UI updates are displayed
//                eventlist.revalidate();
//                eventlist.repaint();
//            });
//
//            itemPanel.add(itemLabel);
//            itemPanel.add(deleteButton);
//            eventlist.add(itemPanel);
//            System.out.println("added "+ item);
//        }
//
//        // In case the list is empty, show a message
//        if (items.isEmpty()) {
//            eventlist.add(new JLabel("No items available."));
//        }
//    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Eventtab = new javax.swing.JTable();
        eventlist = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nametxt = new javax.swing.JLabel();
        phonetxt = new javax.swing.JLabel();
        usernametxt = new javax.swing.JLabel();
        emailtxt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        feedback = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Eventtab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Eventtab);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 580, -1));

        javax.swing.GroupLayout eventlistLayout = new javax.swing.GroupLayout(eventlist);
        eventlist.setLayout(eventlistLayout);
        eventlistLayout.setHorizontalGroup(
            eventlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        eventlistLayout.setVerticalGroup(
            eventlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(eventlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jButton1.setText("Create new event");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nametxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nametxt.setText("Name");
        jPanel1.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 340, -1));

        phonetxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        phonetxt.setText("phone");
        jPanel1.add(phonetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 280, -1));

        usernametxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usernametxt.setText("Username");
        jPanel1.add(usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 380, -1));

        emailtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emailtxt.setText("Email");
        jPanel1.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 370, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 210, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 210, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("phone");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 210, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Username");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 250, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 140));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Registered Events");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 230, -1));

        feedback.setText("View Feedbacks");
        feedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedbackMouseClicked(evt);
            }
        });
        jPanel2.add(feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, -1, -1));

        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 920));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        addevent aevt = new addevent();
        aevt.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1MouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void feedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackMouseClicked
        // TODO add your handling code here:
        feedback_org feed = new feedback_org();
        feed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_feedbackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(org_homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(org_homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(org_homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(org_homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new org_homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Eventtab;
    private javax.swing.JButton back;
    private javax.swing.JLabel emailtxt;
    private javax.swing.JPanel eventlist;
    private javax.swing.JButton feedback;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nametxt;
    private javax.swing.JLabel phonetxt;
    private javax.swing.JLabel usernametxt;
    // End of variables declaration//GEN-END:variables
}
