/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.college_event_management.pages;

import com.mycompany.college_event_management.Utils.MD5;
import com.mycompany.college_event_management.Utils.OrganizerTableModel;
import com.mycompany.college_event_management.Utils.ParticipantTableModel;
import com.mycompany.college_event_management.database.tables.Organizer;
import com.mycompany.college_event_management.database.tables.Participant;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author supru
 */
public class organizer_list extends javax.swing.JFrame {

    /**
     * Creates new form organizer_list
     */
    private List<String> items = new ArrayList<>();
    public organizer_list() {
        initComponents();
                setExtendedState(JFrame.MAXIMIZED_BOTH);

        fetchorg();
    }
    private void clearfields(){
    name.setText(null);
    phone_no.setText(null);
    email.setText(null);
    user_name.setText(null);
    pass.setText(null);
}
   private void fetchorg(){
        var allorgs = Organizer.getAllOrganizers();
        System.err.println("allEvents" + allorgs.size());
        //Table
        OrganizerTableModel model = new OrganizerTableModel(allorgs);
        orgtab.setModel(model);
        
        //Pannel with delete
        for (Organizer e : allorgs) {
          items.add(e.organizerName);
        }
        refreshItemList();
    }
private void refreshItemList() {
        orglist.removeAll();

        for (String item : items) {
            JPanel itemPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
            JLabel itemLabel = new JLabel(item);
            JButton deleteButton = new JButton("Delete");
            deleteButton.addActionListener((ActionEvent e) -> {
                items.remove(item);
                refreshItemList();
                // Revalidate and repaint to ensure UI updates are displayed
                orglist.revalidate();
                orglist.repaint();
            });

            itemPanel.add(itemLabel);
            itemPanel.add(deleteButton);
            orglist.add(itemPanel);
            System.out.println("added "+ item);
        }

        // In case the list is empty, show a message
        if (items.isEmpty()) {
            orglist.add(new JLabel("No items available."));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orgtab = new javax.swing.JTable();
        orglist = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        register1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        org_name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        phone_no = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        org_email = new javax.swing.JLabel();
        org_phone = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        user_name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Organizer details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 360, -1));

        orgtab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Phone", "Email", "Username"
            }
        ));
        orgtab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orgtabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(orgtab);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 590, -1));

        javax.swing.GroupLayout orglistLayout = new javax.swing.GroupLayout(orglist);
        orglist.setLayout(orglistLayout);
        orglistLayout.setHorizontalGroup(
            orglistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        orglistLayout.setVerticalGroup(
            orglistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel1.add(orglist, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 50, 120));

        jPanel3.setBackground(new java.awt.Color(102, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        register1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        register1.setText("Add");
        register1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register1MouseClicked(evt);
            }
        });
        jPanel3.add(register1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 101, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 250, 320));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        name.setText("Name");
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 120, -1));

        org_name.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        org_name.setText("Organizer Name");
        jPanel2.add(org_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 160, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Registration");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 160, 40));

        jButton2.setText("clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 60, 10));

        phone_no.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        phone_no.setText("Phone_no");
        phone_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_noActionPerformed(evt);
            }
        });
        jPanel2.add(phone_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 120, -1));

        email.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        email.setText("Email");
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 120, -1));

        org_email.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        org_email.setText("Organizer Email");
        jPanel2.add(org_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 150, -1));

        org_phone.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        org_phone.setText("Organizer phone ");
        jPanel2.add(org_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        username.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        username.setText("Username");
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 101, -1));

        password.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        password.setText("Password");
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 101, -1));

        pass.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pass.setText("************");
        jPanel2.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 120, -1));

        user_name.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        user_name.setText("Username");
        user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_nameActionPerformed(evt);
            }
        });
        jPanel2.add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 120, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 100, 590, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1517, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1068, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orgtabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orgtabMouseClicked
        // TODO add your handling code here:                               
//    int row = orgtab.getSelectedRow();
//    DefaultTableModel model =(DefaultTableModel) eventtab.getModel();
//    eventId.setText(model.getValueAt(row,0).toString());
//    eventname.setText(model.getValueAt(row,1).toString());
//    venueid.setText(model.getValueAt(row,2).toString());
//    orgid.setText(model.getValueAt(row,3).toString());
//    date.setText(model.getValueAt(row,4).toString());
//    desc.setText(model.getValueAt(row,5).toString());
//}   

    }//GEN-LAST:event_orgtabMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
                    admin_home home = new admin_home();
                    home.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void phone_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_noActionPerformed

    private void user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_nameActionPerformed

    private void register1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register1MouseClicked
        // TODO add your handling code here:
        String hashedPassword = MD5.hashPassword(pass.getText());
        if(name!=null && phone_no!=null && email!=null && user_name!=null){
            Organizer org = new Organizer(0, name.getText(),phone_no.getText(),email.getText(),user_name.getText(),hashedPassword);
            Organizer.insertorganizer(org);
            JOptionPane.showMessageDialog(this, "Register successful", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this, "Register unsuccessful", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        clearfields();

    }//GEN-LAST:event_register1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        clearfields();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = orgtab.getSelectedRow();

// Check if any row is selected
if (selectedRowIndex != -1) {
    // Assuming the organizer ID is stored in the first column of the table
    int organizerIdToDelete = (int) orgtab.getValueAt(selectedRowIndex, 0);
    
    // Ask for confirmation before deleting the organizer
    int confirmDialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this organizer?", "Confirmation", JOptionPane.YES_NO_OPTION);
    
    // Check user's choice
    if (confirmDialogResult == JOptionPane.YES_OPTION) {
        // Attempt to delete the organizer
        boolean deletionSuccessful = Organizer.deleteOrganizer(organizerIdToDelete);

        // Display appropriate message based on deletion result
        if (deletionSuccessful) {
            JOptionPane.showMessageDialog(null, "Organizer deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            // Optionally, refresh the table to reflect the changes
        } else {
            JOptionPane.showMessageDialog(null, "Failed to delete organizer. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
} else {
    // If no row is selected, display an error message
    JOptionPane.showMessageDialog(null, "Please select an organizer to delete.", "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(organizer_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(organizer_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(organizer_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(organizer_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new organizer_list().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JLabel org_email;
    private javax.swing.JLabel org_name;
    private javax.swing.JLabel org_phone;
    private javax.swing.JPanel orglist;
    private javax.swing.JTable orgtab;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel password;
    private javax.swing.JTextField phone_no;
    private javax.swing.JButton register1;
    private javax.swing.JTextField user_name;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
