/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.college_event_management.pages;

import com.mycompany.college_event_management.database.AppState;
import com.mycompany.college_event_management.database.tables.Event;
import javax.swing.JFrame;

/**
 *
 * @author supru
 */
public class addEvent extends javax.swing.JFrame {

    /**
     * Creates new form addEvent
     */
    public addEvent() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        E_name = new javax.swing.JLabel();
        venue = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        event_name = new javax.swing.JTextField();
        venuename = new javax.swing.JTextField();
        date_event = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        submit = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        E_name.setText("Event Name");
        getContentPane().add(E_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 44, 92, -1));

        venue.setText("Venue");
        getContentPane().add(venue, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 81, 92, -1));

        description.setText("Description");
        getContentPane().add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 158, 74, -1));
        getContentPane().add(event_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 38, 142, -1));

        venuename.setText("jTextField2");
        getContentPane().add(venuename, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 78, 142, -1));

        date_event.setText("jTextField3");
        getContentPane().add(date_event, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 118, 142, -1));

        date.setText("Date");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 121, 92, -1));

        desc.setColumns(20);
        desc.setRows(5);
        jScrollPane2.setViewportView(desc);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 158, 253, 103));

        submit.setText("Submit");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 271, -1, -1));

        back.setText("back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
        Event ev = new Event(0, event_name.getText(),venuename.getText(),date_event.getText(), AppState.logedinOrg.organizerId ,desc.getText());
        Event.insertEvent(ev);
        org_homepage homePage = new org_homepage();
        homePage.setVisible(true);
        this.dispose();
                
    }//GEN-LAST:event_submitMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        org_homepage home = new org_homepage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel E_name;
    private javax.swing.JButton back;
    private javax.swing.JLabel date;
    private javax.swing.JTextField date_event;
    private javax.swing.JTextArea desc;
    private javax.swing.JLabel description;
    private javax.swing.JTextField event_name;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton submit;
    private javax.swing.JLabel venue;
    private javax.swing.JTextField venuename;
    // End of variables declaration//GEN-END:variables
}
