/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.college_event_management.pages;

import com.mycompany.college_event_management.database.tables.Organizer;
import javax.swing.JFrame;

/**
 *
 * @author supru
 */
public class admin_home extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin_home() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        org_view = new javax.swing.JButton();
        event_view = new javax.swing.JButton();
        participant_view = new javax.swing.JButton();
        venue_view = new javax.swing.JButton();
        o_register = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Events");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 56, 37, -1));

        jLabel2.setText("Organizers");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 107, 79, -1));

        jLabel3.setText("Participants");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 159, 79, -1));

        jLabel4.setText("Venues");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 208, 79, -1));

        org_view.setText("View");
        org_view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                org_viewMouseClicked(evt);
            }
        });
        getContentPane().add(org_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 100, -1, -1));

        event_view.setText("View");
        event_view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                event_viewMouseClicked(evt);
            }
        });
        event_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                event_viewActionPerformed(evt);
            }
        });
        getContentPane().add(event_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 49, -1, -1));

        participant_view.setText("View");
        participant_view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                participant_viewMouseClicked(evt);
            }
        });
        getContentPane().add(participant_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 152, -1, -1));

        venue_view.setText("View");
        venue_view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                venue_viewMouseClicked(evt);
            }
        });
        getContentPane().add(venue_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 201, -1, -1));

        o_register.setText("add");
        o_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o_registerMouseClicked(evt);
            }
        });
        getContentPane().add(o_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Admin Panel");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 140, -1));

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void event_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_event_viewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_event_viewActionPerformed

    private void event_viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_event_viewMouseClicked
        // TODO add your handling code here:
                   Eventlist_admin elist = new Eventlist_admin();
                   elist.setVisible(true);
                   this.dispose(); 

    }//GEN-LAST:event_event_viewMouseClicked

    private void org_viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_org_viewMouseClicked
        // TODO add your handling code here:
                    organizerList list = new organizerList();
                   list.setVisible(true);
                    this.dispose(); 

    }//GEN-LAST:event_org_viewMouseClicked

    private void participant_viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_participant_viewMouseClicked
        // TODO add your handling code here:
                   Participant_list plist = new Participant_list();
                   plist.setVisible(true);
                    this.dispose(); 
    }//GEN-LAST:event_participant_viewMouseClicked

    private void venue_viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_venue_viewMouseClicked
        // TODO add your handling code here:
        Venuelist venue=new Venuelist();
        venue.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_venue_viewMouseClicked

    private void o_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o_registerMouseClicked
                    register RPage = new register();
                    RPage.setVisible(true);
                    this.dispose(); 
    }//GEN-LAST:event_o_registerMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Login homePage = new Login();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton event_view;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton o_register;
    private javax.swing.JButton org_view;
    private javax.swing.JButton participant_view;
    private javax.swing.JButton venue_view;
    // End of variables declaration//GEN-END:variables
}
