/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.college_event_management.pages;

import com.mycompany.college_event_management.database.AppState;
import com.mycompany.college_event_management.database.tables.Organizer;
import com.mycompany.college_event_management.database.tables.Participant;
import javax.swing.JFrame;

/**
 *
 * @author supru
 */
public class participant_home extends javax.swing.JFrame {

    /**
     * Creates new form participant_home
     */
    public participant_home() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        Participant loggedinpart = AppState.logedingpart;
        namevalue.setText(loggedinpart.ParticipantName);
        emailvalue.setText(loggedinpart.Participantemail);
        phonevalue.setText(loggedinpart.ParticipantPhone);
        usernamevalue.setText(loggedinpart.ParticipantUsername);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unregistered_event = new javax.swing.JButton();
        registered_event = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nametext = new javax.swing.JLabel();
        emailtext = new javax.swing.JLabel();
        phonetext = new javax.swing.JLabel();
        usernametext = new javax.swing.JLabel();
        namevalue = new javax.swing.JLabel();
        emailvalue = new javax.swing.JLabel();
        phonevalue = new javax.swing.JLabel();
        usernamevalue = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        unregistered_event.setText("view");
        unregistered_event.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unregistered_eventMouseClicked(evt);
            }
        });
        unregistered_event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unregistered_eventActionPerformed(evt);
            }
        });
        getContentPane().add(unregistered_event, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 202, -1, -1));

        registered_event.setText("view");
        registered_event.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registered_eventMouseClicked(evt);
            }
        });
        registered_event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registered_eventActionPerformed(evt);
            }
        });
        getContentPane().add(registered_event, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jLabel1.setText("Participant Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 190, -1));

        jLabel3.setText("Registered event");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel4.setText("Unregistered event");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 120, -1));

        nametext.setText("name:");
        getContentPane().add(nametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        emailtext.setText("email:");
        getContentPane().add(emailtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 20));

        phonetext.setText("phone:");
        getContentPane().add(phonetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        usernametext.setText("username:");
        getContentPane().add(usernametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        namevalue.setText("name");
        getContentPane().add(namevalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        emailvalue.setText("email");
        getContentPane().add(emailvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        phonevalue.setText("phone");
        getContentPane().add(phonevalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        usernamevalue.setText("username");
        getContentPane().add(usernamevalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registered_eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registered_eventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registered_eventActionPerformed

    private void unregistered_eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unregistered_eventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unregistered_eventActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
    Login homePage = new Login();
    homePage.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void registered_eventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registered_eventMouseClicked
        // TODO add your handling code here:
                    registeredevents reg_e = new registeredevents();
                    reg_e.setVisible(true);
                    this.dispose(); 
    }//GEN-LAST:event_registered_eventMouseClicked

    private void unregistered_eventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unregistered_eventMouseClicked
        // TODO add your handling code here:
                    unregistered_events reg_e = new unregistered_events();
                    reg_e.setVisible(true);
                    this.dispose(); 
    }//GEN-LAST:event_unregistered_eventMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(participant_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(participant_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(participant_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(participant_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new participant_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel emailtext;
    private javax.swing.JLabel emailvalue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel nametext;
    private javax.swing.JLabel namevalue;
    private javax.swing.JLabel phonetext;
    private javax.swing.JLabel phonevalue;
    private javax.swing.JButton registered_event;
    private javax.swing.JButton unregistered_event;
    private javax.swing.JLabel usernametext;
    private javax.swing.JLabel usernamevalue;
    // End of variables declaration//GEN-END:variables
}
